title: Systems and Layers
tagline: Deep dives into systems topics — written from first principles, built hands-on.
description: Deep dives into systems topics — written from first principles, built hands-on.
url: "https://ajit3259.github.io"
baseurl: "/systems-and-layers"

author:
  name: Ajit Kumar
  url: https://github.com/ajit3259

avatar: /images/systems_and_layers_sq.png

social:
  name: Ajit Kumar
  email: ajitkumar3259@gmail.com
  links:
    - https://github.com/ajit3259

theme: jekyll-theme-chirpy

timezone: Asia/Kolkata

paginate: 10
paginate_path: "/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-archives

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

permalink: /:categories/:title/

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: ajit_kumar
  - scope:
      path: ""
      type: tabs
    values:
      layout: page

exclude:
  - README.md
  - api-patterns/code/rest-server/
  - api-patterns/code/sse-server/
  - api-patterns/code/ws-server/
  - api-patterns/code/grpc-server/
  - api-patterns/code/graphql-server/
  - api-patterns/code/mqtt-server/
  - node_modules/
  - "*/node_modules/"
  - "*/dist/"
  - "*/package.json"
  - "*/package-lock.json"
  - "*/tsconfig.json"
